# Generated by Django 4.0.5 on 2022-06-18 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='书名')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='图书介绍')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('imgdir', models.ImageField(blank=True, null=True, upload_to='./img_database', verbose_name='图像路径')),
                ('translator', models.CharField(blank=True, max_length=50, null=True, verbose_name='译者')),
                ('isbn', models.CharField(max_length=15, verbose_name='ISBN号')),
                ('chinaclass', models.CharField(max_length=10, verbose_name='中图分类号')),
                ('binding', models.CharField(blank=True, max_length=20, null=True, verbose_name='装帧')),
                ('language', models.CharField(blank=True, max_length=20, null=True, verbose_name='语言')),
                ('publisherAddress', models.CharField(blank=True, max_length=20, null=True, verbose_name='出版地')),
                ('price', models.CharField(blank=True, max_length=40, null=True, verbose_name='定价')),
                ('publisher', models.CharField(blank=True, max_length=40, null=True, verbose_name='出版社')),
                ('isbn10', models.CharField(max_length=10, verbose_name='10位ISBN号')),
                ('page', models.CharField(blank=True, max_length=6, null=True, verbose_name='页数')),
                ('category', models.SmallIntegerField(choices=[(0, '马克思主义、列宁主义、毛泽东思想、邓小平理论'), (1, '哲学、宗教'), (2, '社会科学总论'), (3, '政治、法律'), (4, '军事'), (5, '经济'), (6, '文化、科学、教育、体育'), (7, '语言、文字'), (8, '文学'), (9, '艺术'), (10, '历史、地理'), (12, '自然科学总论'), (14, '数理科学和化学'), (15, '天文学、地球科学'), (16, '生物科学'), (17, '医药、卫生'), (18, '农业科学'), (19, '工业技术'), (20, '交通运输'), (21, '航空、航天'), (23, '环境科学、安全科学'), (25, '综合性图书')], verbose_name='类别')),
                ('pubdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(choices=[(0, '还书'), (1, '借书')], verbose_name='状态')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('bookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.book')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
        ),
    ]
