# Generated by Django 4.0.5 on 2022-06-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_book_chinaclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '马克思主义、列宁主义、毛泽东思想、邓小平理论'), (1, '哲学、宗教'), (2, '社会科学总论'), (3, '政治、法律'), (4, '军事'), (5, '经济'), (6, '文化、科学、教育、体育'), (7, '语言、文字'), (8, '文学'), (9, '艺术'), (10, '历史、地理'), (11, '其他'), (12, '自然科学总论'), (14, '数理科学和化学'), (15, '天文学、地球科学'), (16, '生物科学'), (17, '医药、卫生'), (18, '农业科学'), (19, '工业技术'), (20, '交通运输'), (21, '航空、航天'), (23, '环境科学、安全科学'), (25, '综合性图书')], verbose_name='类别'),
        ),
    ]
