# Generated by Django 4.0.5 on 2022-06-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='onboard',
            field=models.BooleanField(default=True, verbose_name='在架上'),
        ),
    ]
